### ISSUE TITLE
Allow schema to be a callable 

### ISSUE THREAD

**Issue by bhch** [bhch/django-jsonform#1]
This would allow us to dynamically return the `choices` such as objects from the database.

This would also allow us to return a schema based on user permissions.

**Comment by bhch** [comment]
This feature has been added in v2.1.0.

**Comment by Mekagojira8** [comment]
I have a model like this
`class Model(models.Model):    
    json_schema = models.JSONField(default=dict) # editable by the user
    json_value = JSONField(schema='whatever is in json_schema') # django_jsonform's field
`
how do I pass in a callable to `schema` that can actually fetch the `json_schema` value of the same row? Is it possible? Essentially I need the entire schema to be user editable.

Sorry if this is a basic question, thank you in advance

**Comment by bhch** [comment]
You'll need to pass the current model instance to the callable.

It's documented here: [Accessing model instance in callable schema](https://django-jsonform.readthedocs.io/en/latest/fields-and-widgets.html#accessing-model-instance-in-callable-schema).

It's a bit of a manual work as you'll have to override the admin's model form.

I would have loved to provide an automatic way to pass the current model instance, but that's not possible due to the way Django initializes model fields and widgets.

See also: #8.
