### ISSUE TITLE
Trouble with Schema: Combining `anyOf` and `additionalProperties`

### ISSUE THREAD

**Issue by john2022wick** [bhch/django-jsonform#103]
Hello everyone,

I am a beginner and currently facing a problem:

I would like to save arbitrary defined content in a JsonField, so I configured an empty dict and used `additionalProperties` to edit its content.

The schema is similar to:
```json
{
  "type": "object",
  "title": "some desc",
  "keys": {},
  "additionalProperties": {
    "anyOf": [
      {
        "type": "integer",
        "title": "integer text"
      },
      {
        "type": "string",
        "title": "string text",
        "helpText": "help text",
        "placeholder": "some thing to display"
      },
      {
        "type": "boolean",
        "title": "boolean"
      }
    ]
  }
}
```

When I test it in the playground, 
`anyOf` or `oneOf` don't work with `additionalProperties`. 
The newly added properties cannot be removed.

The documentation mentions that `allOf` can work with `additionalProperties`, 
but when I test it, the newly added properties missing selectable types.

What should I do? Can anyone help me?

**Comment by bhch** [comment]
Can you provide the `allOf` schema example?

**Comment by bhch** [comment]
I'm going to close this issue because of lack of activity. If you wish, you can comment and reopen.
