### ISSUE TITLE
If additionalProperties is used with dict, the title field overrides the dict key in the display

### ISSUE THREAD

**Issue by alexgmin** [bhch/django-jsonform#114]
With this schema:

```
{
    'type': 'dict',
    'title': 'Language ISO 2 letter code',
    'properties': {},
    'additionalProperties': {
        'type': 'dict',
        'title': 'Translation',
        'properties': {},
        'additionalProperties': {
            'type': 'string',
        },
    },
}
```

This happens:

![image](https://github.com/bhch/django-jsonform/assets/8340441/84b665d6-6876-4cd1-bf78-15d88590bb65)

If we remove ` 'title': 'Translation',`

The language key of the additional property is shown

![image](https://github.com/bhch/django-jsonform/assets/8340441/e45c2df5-dfdb-4320-b51c-154c5501721b)

So we cannot use title and see the additional key at the same time.

**Comment by bhch** [comment]
Isn't that expected, though? The `title` should replace the display name of a key. This is how it works for predefined keys as well.

**Comment by alexgmin** [comment]
It makes sense in predefined keys because those are static, and also in the items of a list.
But in additional properties this happens:

![image](https://github.com/bhch/django-jsonform/assets/8340441/a967586b-e176-4a48-b28c-3067812ac67c)

Internally the json is
```
{
    "bar":
    {
        "Original name": "translated_name"
    },
    "foo":
    {
        "original_name": "translated_name"
    }
}
```

There's no way no know in the admin which additional key you're editing.

In our case due to a lack of help_text for this, we're using the title for to provide that information.

**Comment by bhch** [comment]
I'll add support for `help_text` or the `description` keyword which is already a part of the standard JSON Schema spec.

It will be displayed right below the title (key name).

Will that work for you?

**Comment by alexgmin** [comment]
That would work for us.

Will the title still override the key name in additionalProperties? 
With `help_text` o `description` our use case will still be solved, but I still think that using title shouldn't hide the dynamic keys.

**Comment by bhch** [comment]
See my comment on https://github.com/bhch/django-jsonform/issues/115#issuecomment-1649556562

**Comment by alexgmin** [comment]
> See my comment on [#115 (comment)](https://github.com/bhch/django-jsonform/issues/115#issuecomment-1649556562)

I understood that as removing the "beautifying" of the title only, not removing it completely, my bad. Then yeah, the solution will work.

**Comment by bhch** [comment]
> Will the title still override the key name in additionalProperties?  
> ...  
> but I still think that using title shouldn't hide the dynamic keys.

Yes, if a title is provided it will override the key for display text.

The problem with displaying both is deciding on a format, such as:

 - `<key> - <title>` — key before title
 - `<title> - <key>` — title before key
 -  `<key> (<title>)` — title in parenthesis
 - `<key> <title>` — no dash

Everybody will have different requirements. This will require some sort of string formatting.

Maybe I'll consider adding it in future, but not right now.

**Comment by bhch** [comment]
Added support for the `description` keyword in [v2.18.0](https://github.com/bhch/django-jsonform/releases/tag/v2.18.0). Please upgrade and test it out.

Thank you for reporting the issue.
