### ISSUE TITLE
Add ability to see selected values in a multi choice

### ISSUE THREAD

**Issue by llybin** [bhch/django-jsonform#116]
Hello. Thanks for the lib.

https://bhch.github.io/react-json-form/playground/#5-multi-select-choices

Is it possible to add ability to see selected values in a multi choice? Maybe as optional parameter.
![image](https://github.com/bhch/django-jsonform/assets/5445357/8c651e23-65fa-4578-9b28-db3e882cd793)
I would like to see the selected values, it's not convenient for me click every time on the field to see what is there.
![image](https://github.com/bhch/django-jsonform/assets/5445357/5410cf9a-e6a5-418e-8245-5fa8c80242a8)

**Comment by bhch** [comment]
Could you give me an example of the UI, like where should the selected options be displayed?

**Comment by llybin** [comment]
For example like that:
https://www.npmjs.com/package/react-select
https://react-select.com/home

Here is can see the chosen values without opening dropdown list.
![image](https://github.com/bhch/django-jsonform/assets/5445357/9e05145a-a0c1-4782-b111-87327d0ced68)

**Comment by bhch** [comment]
Alright, I'll try to get this feature out in the next release.

**Comment by bhch** [comment]
Released in [v2.19.0](https://github.com/bhch/django-jsonform/releases/tag/v2.19.0). Please upgrade and test it out.

Thank you.
