### ISSUE TITLE
Error message for uniqueItems is not readable

### ISSUE THREAD

**Issue by maciejpolanczyk** [bhch/django-jsonform#117]
Error message for uniqueItems is not shown below/next to the field. In addition current error message is unclear.
Current state:
<img width="551" alt="Screenshot 2023-08-09 at 11 06 46" src="https://github.com/bhch/django-jsonform/assets/20277154/c538ddc8-e92c-4ba5-97b3-266c24684d89">

Code:
```
class ShoppingList(Model):
    data = JSONField(
        schema={
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": True
        }
    )

admin.site.register(ShoppingList)
```

Expected state: show clear message next to the field

Used:
django = "==4.2.3"
django-jsonform = "==2.18.0"

**Comment by bhch** [comment]
Fixed in [v2.19.0](https://github.com/bhch/django-jsonform/releases/tag/v2.19.0). Please upgrade and test it out.

Thank you.
