### ISSUE TITLE
Radio button displayed incorrectly

### ISSUE THREAD

**Issue by maciejpolanczyk** [bhch/django-jsonform#118]
<img width="1113" alt="Screenshot 2023-08-11 at 08 03 55" src="https://github.com/bhch/django-jsonform/assets/20277154/c2a852fa-b150-403c-90da-7c16312ffb33">

Used:
django = "==4.2.3"
django-jsonform = "==2.18.0"
chrome 115.0.5790.170 (Official Build) (x86_64)

**Comment by bhch** [comment]
Fixed in [v2.19.0](https://github.com/bhch/django-jsonform/releases/tag/v2.19.0). Please upgrade and test it out.

Thank you.
