### ISSUE TITLE
Empty value for integer field is a string

### ISSUE THREAD

**Issue by mick88** [bhch/django-jsonform#12]
How do I define a field as optional? I'm trying to add an integer field, but i cannot save the form without putting in value.

**Comment by bhch** [comment]
All fields are optional by default. I'm not sure what's wrong.

Could you post a sample schema for me to reproduce this?

**Comment by mick88** [comment]
I just realized that my problem is not with field being required, it's that the empty value for "int" field is stored as an empty string. This fails my model validation that asserts the value to be either `None` or an integer instance. Because it's a string, the validation fails.

Here's the relevant schema:

```python
    {
        'type': 'object',
        'keys': {
            ...
            'team_id': {
                'type': 'integer',
            },
            ...
        },
    }
```

The error I'm getting:
![image](https://user-images.githubusercontent.com/4239561/142609176-57189c8b-eeb3-40d5-abc0-65612ad82605.png)

**Comment by bhch** [comment]
I've built this using React and the convention is to use empty string for blank number inputs.

But I agree it doesn't make sense to use string for integer field. I'll fix it soon.

**Comment by bhch** [comment]
I've fixed this issue and released a new version ([v.2.5.0](https://github.com/bhch/django-jsonform/releases/tag/v2.5.0)).

Please upgrade using `pip install -U django-jsonform`.

Also, remember to refresh browser cache to load updated js files.

Thank you for reporting this issue.
