### ISSUE TITLE
Support for related objects in Dropdown

### ISSUE THREAD

**Issue by wlisesrivas** [bhch/django-jsonform#122]
Hi all,

Not sure if there is support for a list/dropdown from existing objects (like django admin do for related objects)
![image](https://github.com/bhch/django-jsonform/assets/1482092/8da3123e-4e1c-4cdc-964d-ac81e864de54)

**Comment by bhch** [comment]
See the docs on [Dynamic choices](https://django-jsonform.readthedocs.io/en/latest/guide/choices.html#dynamic-choices).

**Comment by bhch** [comment]
I believe I've answered your question. So I'm going to close it due to lack of activity.
