### ISSUE TITLE
Allow autocomplete when using multiselect

### ISSUE THREAD

**Issue by maciejpolanczyk** [bhch/django-jsonform#124]
Can you enable autocomplete feature for arrays with mutliselect? 
Currently you can have one or the other, would be great to have both together

**Comment by bhch** [comment]
Alright. Maybe in next couple of releases.

**Comment by bhch** [comment]
This feature is released in [v2.20.0](https://github.com/bhch/django-jsonform/releases/tag/v2.20.0). Please upgrade and test it out.

Thank you.
