### ISSUE TITLE
Default layout of jsonform in Django Admin

### ISSUE THREAD

**Issue by gersmann** [bhch/django-jsonform#135]
Thank you for the great library. One question, when I've set up django-jsonform I am gettting a pretty narrow form with also narrow containers for field labels. I was wondering if this is how it is supposed ot be rendered or if I made a mistake in the setup. 

This is how the admin form looks for me:
<img width="563" alt="image" src="https://github.com/bhch/django-jsonform/assets/2694872/2ef5a27e-2fcf-49ec-b7f7-bf4e5110d3ba">

**Comment by bhch** [comment]
Could you tell me which Django version are you using so I can try to reproduce this?

**Comment by gersmann** [comment]
This is on Django 4.2.9, a blank sample project I created.

**Comment by bhch** [comment]
I'm able to reproduce it.

The form is wider in Django v3.x but it appears they have made some changes in admin's CSS in v4.x which is making the form narrow.

I'll try to release a fix soon.

Thank you for reporting this issue.

**Comment by bhch** [comment]
This has been fixed in [v2.21.3](https://github.com/bhch/django-jsonform/releases/tag/v2.21.3). Please update and test it out.

Thank you.
