### ISSUE TITLE
Setting JSONField schema dynamically

### ISSUE THREAD

**Issue by ErikKoinberg** [bhch/django-jsonform#145]
I have a situation where a user needs to define a template structure for something. Based on the data in this first JSONField, I am able to create a new schema dynamically, derived from the user input into the first model. 

The thing now is that I want to set this derived schema to be the Schema for a JSONField of the instance of another Model (which has a foreignkey to the first model). Is this possible in any way? I found it hard to implement since: 

 `field =JSONField(schema = my_schema) `

Is declared class-wise for the model. Is there any way to change the schema of the JSONField of an instance of a model containing a django-jsonform JSONField? Otherwise, is there a workaround for this?

**Comment by ErikKoinberg** [comment]
I was able to solve this by reading about callable schemas as described in a previous issue. I did however use the hacky version and could not find a cleaner implementation in the docs.

**Comment by bhch** [comment]
>  I did however use the hacky version and could not find a cleaner implementation in the docs.

Could you give me an example of what a cleaner implementation would look like?

Thanks.

**Comment by ErikKoinberg** [comment]
I understand. Actually, it was fine and not that hard to do. And it works.
