### ISSUE TITLE
Add button to open link in URLField

### ISSUE THREAD

**Issue by WillNilges** [bhch/django-jsonform#156]
I have a bit of an unusual use case for django admin. In my project, we track the hardware for internet installs, and as part of that, we have a Building Model that posesses an array of URLs that point to panoramic photos of the roof.

![image](https://github.com/bhch/django-jsonform/assets/42927786/0f74b655-502b-44bb-b94e-da5497748d1d)

I can display them real nice in the panel like so, but I would like to add a button to each entry to allow me to open that link in a new tab. I'm considering just editing the template, but I am also wondering if there's a more elegant way to do so?

**Comment by WillNilges** [comment]
Doing a bit of research (just steam-of-conciousness) it looks like this is where the TextInput is added:
https://github.com/bhch/django-jsonform/blob/master/django_jsonform/forms/fields.py#L92

Is there a way to override that in this library?

**Comment by WillNilges** [comment]
Oh wait, oops. This is built on top of https://github.com/bhch/react-json-form/ (!!), so to make that happen _in the widget itself_ would require editing JS...

Probably somewhere around here: https://github.com/bhch/react-json-form/blob/master/src/ui.js#L170

**Comment by bhch** [comment]
Yeah, seems like a good UX featur to make a clickable link from the input values. I'll try to get it out in the next release.

**Comment by bhch** [comment]
Hello, just following up on this feature.

In your example image, are these inputs all URLFields within an ArrayField?

**Comment by bhch** [comment]
Released in [v2.22.0](https://github.com/bhch/django-jsonform/releases/tag/v2.22.0). Please upgrade and test it out.

CSS improvements may come in a future release.

Thanks.
