### ISSUE TITLE
Weird validation in Django Admin when using array + choice + multiselect

### ISSUE THREAD

**Issue by AlTosterino** [bhch/django-jsonform#171]
Hey!

I encountered a strange validation behavior when using the below schema:

```json
{
    "type": "object",
    "keys": {
        "source_ids": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "widget": "multiselect",
                "title": "Source fields",
                "choices": [
                    {"title": "Test", "value": "b7f368af-a173-4079-8348-e1b9625f220f"},
                    {"title": "Test 2", "value": "277d180c-7be0-495a-8685-340e08734599"},
                ],
            },
        }
    },
}
```
When trying to save the form, validation correctly shows: `Minimum 1 items required.`
But it's setting up the initial values of the dropdowns to empty string, see below:

![Zrzut ekranu 2024-06-21 o 14 33 45](https://github.com/bhch/django-jsonform/assets/25869901/76b5682e-98e4-4314-b0dc-6729609be681)

When saving the form again, validation correctly shows: `Invalid choice`

![image](https://github.com/bhch/django-jsonform/assets/25869901/3442ea83-3b6e-499d-b9fa-02e0caefc60d)

Using `widget.validate_on_submit=True` helps with the first problem (setting initial values for dropdowns) but it does not behave correctly with the `choices`, see below

![image](https://github.com/bhch/django-jsonform/assets/25869901/2c984f40-55a7-4f06-8476-ab88455afd52)

Expected behavior:
- Validation error shows: Minimum 1 items required.
- Dropdows stays empty

**Comment by bhch** [comment]
Released in [v2.23.0](https://github.com/bhch/django-jsonform/releases/tag/v2.23.0).
