### ISSUE TITLE
Support datetime format(s) for strings

### ISSUE THREAD

**Issue by alexgmin** [bhch/django-jsonform#19]
A basic feature would be to add the format to the string type returned by datetime.datetime.isoformat()

This would require a datetime picker in the admin.

A more advanced way to do it would be to allow custom datetime formats, like "YYYY-MM-DD HH:MM", but this is more complicated and with the basic feature anybody could extend the field and format the datetime into their desired format

I love the package, btw!.

**Comment by bhch** [comment]
I've implemented this feature. I'll release a new version soon.

**Comment by bhch** [comment]
I've released this feature in [version 2.8.0](https://github.com/bhch/django-jsonform/releases/tag/v2.8.0). Please upgrade and test it out.

**Comment by alexgmin** [comment]
Seems to work correctly.

Thank you so much!

**Comment by bhch** [comment]
Currently, it's just a basic implementation. I'll improve it later with a more uniform ui.
