### ISSUE TITLE
editor.html template is missing

### ISSUE THREAD

**Issue by mick88** [bhch/django-jsonform#2]
I installed version 2.1.0 of the lib in my project and followed the [quickstart ](https://django-jsonform.readthedocs.io/en/stable/quickstart.html) tutorial, but I am now getting an error in the page where the field is supposed to render - template "django_jsonform/editor.html" does not exist. I checked that there's no "templates" directory in the locally installed `django_jsonform` package. The only folders are models and forms and the template is being referenced in `JSONFormWidget`.

**Comment by bhch** [comment]
I've released a new version fixing this issue. Please upgrade using `pip install -U django-jsonform`.
