### ISSUE TITLE
Improve Django version check

### ISSUE THREAD

**Issue by rglsk** [bhch/django-jsonform#23]
The current check works only for Django 3.xxx:

```
django.VERSION[0] >= 3 and django.VERSION[1] >= 1:
```

Recently a new Django version was released 4.0..., with the old check the package is not working because of:  `django.VERSION[1] >= 1`

**Comment by rglsk** [comment]
@bhch May I ask you for review and merge if possible? 💪

**Comment by bhch** [comment]
Fixed in #24.

**Comment by bhch** [comment]
I've released a new version ([v2.7.0](https://github.com/bhch/django-jsonform/releases/tag/v2.7.0. Please upgrade.

Thank you for the PR.
