### ISSUE TITLE
issue button display with Django-Grappelli

### ISSUE THREAD

**Issue by areski** [bhch/django-jsonform#34]
The `Add new` button is not showing up properly, it might be an issue when using with Django-Grappelli:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/53455/164446592-33257ea0-112a-498f-82c4-9266e35b0027.png">

**Comment by bhch** [comment]
Hi, thanks for the issue.

I'll issue a fix soon. Hopefully by tomorrow.

**Comment by areski** [comment]
Thanks for the quick feedback

**Comment by areski** [comment]
It works like a charm, thank you!

**Comment by bhch** [comment]
I'll include this in the next version. It's almost done.

**Comment by bhch** [comment]
Released the fix in [v2.9.0](https://github.com/bhch/django-jsonform/releases/tag/v2.9.0). Please upgrade.
