### ISSUE TITLE
Dropdown not appearing in admin page when setting a default value in model.

### ISSUE THREAD

**Issue by mazerius** [bhch/django-jsonform#41]
Hi, 

I've been using this package due to the very friendly UI on the admin page + it substitutes the ArrayField which would crash all my sqlite3 unit tests (my actual DB is PostgreSQL). 

However, I noticed that once I add a 'default=dict', or any callable for that matter, then the dropdown no longer works on django admin: clicking the '+' does nothing. 

Is this a bug? If not, could you provide me an example of how to specify a default value in my model for the JSONField? 

Thanks!

**Comment by bhch** [comment]
Please give me some sample code to reproduce this.

**Comment by mazerius** [comment]
You're absolutely right, it was a mismatch between the type in my schema and the default: 'array' in schema, but 'dict' default. 
I've now changed my default to a python list too, since I only care about the keys and not the values. 

Thanks a lot for the swift and clear communication, really appreciate it!
