### ISSUE TITLE
Choice field returning empty values

### ISSUE THREAD

**Issue by kayesn786** [bhch/django-jsonform#42]
Hi @bhch 

I have a form displaying the following address information. The state choices is filled based on country through jQuery. 
The problem is, the address object in DB is empty i.e. {country:"",state:""}.

Am i missing something? 

django version: 3.2
using jazzmin for the dashboard UI

ADDRESS={
        "type": "dict",
        "keys": {
            "country": {
                "type": "string",
                'choices': ['India','China',....]
            },
            "state": {
                "type": "string",
                'choices': []
            }
        }
    } 

//models.js
address = JSONField(schema=ADDRESS)

**Comment by bhch** [comment]
Are you populating the `state` input field using JQuery?

**Comment by kayesn786** [comment]
Yes!
But I tried with static values in state too. It is still same as using jQuery

**Comment by bhch** [comment]
The actual JSON data is kept in a hidden textarea. So modifying the input field with jQuery will not change the data.

But it's strange that it's not working with predefined values either. Could you tell me which version you're using?

Check it with this command:

```
$ python -c "import django_jsonform; print(django_jsonform.__version__)"
```

**Comment by bhch** [comment]
I tried the schema you gave me but I'm unable to reproduce this issue. It's working fine for me.

If you could create a sample repository with some code to reproduce this, it'll be quicker for me to just clone and test it out.

**Comment by bhch** [comment]
@kayesn786 Do you still have this issue?

Currently, I'm working on a new version. I've been thinking about providing some JavaScript apis to control the form in the browser, such as  events handlers and functions etc. Those will be useful in cases like this issue.

If you have any ideas, I'd appreciate your input.

**Comment by kayesn786** [comment]
@bhch the issue was with adding dynamic options with jQuery. Django was not recognizing those dynamically added <options/>.
The solution was to pass all possible options while form is rendered and hide then on document load.

However, I would love to have a feature that selects a schema based on some other field in the form.

**Comment by bhch** [comment]
Hi, I've added a basic JavaScript API ([see docs](https://django-jsonform.readthedocs.io/en/stable/guide/javascript.html)) which will allow you to dynamically update the schema and the widget.

Please upgrade to [v2.11.0](https://github.com/bhch/django-jsonform/releases/tag/v2.11.0) and test it out.

---

In future, I'll add support for [`if-then-else`](https://json-schema.org/understanding-json-schema/reference/conditionals.html) keywords in the schema.

**Comment by houtadono** [comment]
I had the same issue with django-jsonform and Jazzmin. The root cause is that Select2 fires jQuery change events, which React's synthetic event system doesn't catch.

Here is how I fixed it globally by adding this snippet to Jazzmin's custom_js in settings.py:
```
$(document).on('change', '.django-jsonform-container select', function (e) {
    if (e.originalEvent === undefined) {
        this.dispatchEvent(new Event('change', {bubbles: true}));
    }
});
```
And in settings.py:

```
JAZZMIN_SETTINGS = {
    # ...
    "custom_js": "js/your_script.js",
}
```
This bridges the gap between Select2 and React's state updates perfectly!"
