### ISSUE TITLE
Default not being respected

### ISSUE THREAD

**Issue by lokeshwarobuli** [bhch/django-jsonform#45]
`weekend_days = JSONField(
        blank=True,
        help_text="Days of the week which are considered weekend days (format is DAY_NAME:1, eg. sunday:1)",
        schema={
            "type": "dict",
            "keys": {
                "monday": {"type": "number", "default": 1},
                "tuesday": {"type": "number", "default": 0},
                "wednesday": {"type": "number", "default": 0},
                "thursday": {"type": "number", "default": 0},
                "friday": {"type": "number", "default": 0},
                "saturday": {"type": "number", "default": 1},
                "sunday": {"type": "number", "default": 1},
            },
        },
    )`
    
    In the above scenario, the weekend_days when complied sets to null, instead of 0, so when I query I get
    ` {
                "monday": 1,
                "tuesday": null,
                "wednesday": null,
                "thursday": null,
                "friday": null,
                "saturday":1,
                "sunday":1,
       }`
   I use Django 4.1, postgres 13, django-jsonform 2.10.1

**Comment by bhch** [comment]
Hi, thank you for reporting this issue.

I've found the cause of the bug, it's an easy fix. However, it won't be released until a few days later. I'm already working on a new version, so I'll release the fix along with that (hopefully by the end of this week). I hope you don't have any urgent requirements.

**Comment by lokeshwarobuli** [comment]
Thanks @bhch Looking forward to the new version !! Cheers

**Comment by bhch** [comment]
Fixed in [v2.11.0](https://github.com/bhch/django-jsonform/releases/tag/v2.11.0). Please upgrade.
