### ISSUE TITLE
multiselect not work

### ISSUE THREAD

**Issue by zN3utr4l** [bhch/django-jsonform#46]
django-jsonform version: 2.10.1
django version: 3.2.14

I have this model field which is an array imported from django_jsonform.models.fields, I would like it to be shown in the admin panel as a multiselector of another model, a kind of Foreign Key where, however, I go to save only the ids of the selected models.

![image](https://user-images.githubusercontent.com/73225008/183918568-cd2a9586-2062-4f6e-9d86-57a10677628d.png)

In my admin form I first tried to do a test with the choices you see here, but i can't select anything.

PS. radio widget works

![image](https://user-images.githubusercontent.com/73225008/183918474-3514a4d3-c1fe-4adc-a7ad-0bc3129b2459.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/73225008/183921024-f0643cec-b18e-414f-996b-9f04a576e8a2.gif)

Another question:
![image](https://user-images.githubusercontent.com/73225008/183926292-c60b1233-dab2-4e96-8563-48a890ac22c3.png)

another question, how do I increase the size of the input?

widget.attrs = {'style': 'width: 275px;'}
it does not work

**Comment by bhch** [comment]
Hello, thank you for reporting this issue.

I've found the cause of the issue. It only happens on top-level arrays. If the array is nested inside an object or another array, then everything works fine.

I will fix this soon and release a new version by the end of this week.

---

Regarding changing the size of the input, you'll have to provide a CSS file with your custom styling through admin's or form's `Media` class.

Also, using `widget.attrs` will only affect the outer container of the JsonFormWidget. But it seems you want to change the size of the input field. In that case you'll have to provide a custom CSS file.

There should be a more elegant solution for custom styling and I'll see what can be done about it.

**Comment by zN3utr4l** [comment]
if I wanted the fields in the multiselect to change dynamically based on another field, i.e. I choose the country of Italy in select1 and in select2, which would be an array field of django-jsonform, all the [{'label': Rome, 'value': 1}, ....]
would dynamically choices be possible? because I imagine that having a fixed schema for the widget this is not possible, the only way I can think of is to override where the select choices are checked in the schema.

To load the dictionary ​​'label' and 'value', could it be done with JQuery or JS, or could it be done somehow with this package?

**Comment by bhch** [comment]
Currently, that is not possible.

But I will expose some methods and events to control the form widget using JS. This would allow for dynamically modifying the schema in the browser and updating the widget.

**Comment by zN3utr4l** [comment]
Ok thanks, so I'm looking forward to this weekend for the top level array fix and future updates for dynamic array loading

**Comment by bhch** [comment]
Fixed in [v2.11.0](https://github.com/bhch/django-jsonform/releases/tag/v2.11.0). Please upgrade.
