### ISSUE TITLE
Django Model not respecting the default if it is 0

### ISSUE THREAD

**Issue by lokeshwarobuli** [bhch/django-jsonform#49]
weekend_days = JSONField(schema={
                                                                  "type": "dict",
                                                                  "keys": {
                                                                    "monday": {
                                                                      "type": "number",
                                                                      "default": 0
                                                                    },
                                                                    "tuesday": {
                                                                      "type": "number",
                                                                      "default": 0
                                                                    }
                                                                  }
                                                                } )

I use `Django 4.1, Django json form 2.10.1`. So, when I run the above as a model field in Django, instead of setting `0 as default` value for keys Monday, Tuesday, the `Django-jsonform` sets `Null` as the value which is not expected

**Comment by bhch** [comment]
It's the same as #45. I've fixed it and I'm preparing the new release. Should be out tomorrow. I've a couple of minor bugs to fix and some docs to update.

**Comment by bhch** [comment]
Fixed in [v2.11.0](https://github.com/bhch/django-jsonform/releases/tag/v2.11.0). Please upgrade.
