### ISSUE TITLE
Docs not clear on what needs to be done in admin.

### ISSUE THREAD

**Issue by johanneswilm** [bhch/django-jsonform#50]
It took me a while to figure out that I had to register the model like this in the admin.py file in order for it to show up correctly:

```py
class ModelNameForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["field_name"].widget.instance = self.instance

    class Meta:
        model = ModelName
        exclude = []


class ModelNameAdmin(admin.ModelAdmin):
    form = ModelNameForm


admin.site.register(ModelName, ModelNameAdmin)
```

It was hard to find that part in the documentaiton and when I found it, the documentation was incomplete.

**Comment by bhch** [comment]
Are you referring to this section: [Accessing model instance in callable schema](https://django-jsonform.readthedocs.io/en/latest/fields-and-widgets.html#accessing-model-instance-in-callable-schema)?

Yeah, the code example is certainly missing the `super()` call and the `Meta` class. I'll fix it.

**Comment by johanneswilm** [comment]
Yes, I tried searching for it, but couldn't find it again.
