### ISSUE TITLE
[Suggestion] Foreign key field

### ISSUE THREAD

**Issue by grayhong** [bhch/django-jsonform#52]
Hello! Thanks for sharing awesome library!

I came up with idea of extending the library to support foreign key id property field and select id using django's default [autocomplete_field](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) UI.

For example,
json schema would be like
```
{
        '$schema': 'http://json-schema.org/schema#',
        'type': 'array',
        'items': {
            'type': 'object',
            'required': [
                "model_id", "field"
            ],
            'properties': {
                'model_id': { -> foreign key id, maybe type should be `ExampleModel` or something else.
                    'title': 'entity',
                    'type': 'number',
                },
                'field': {
                    'title': 'field',
                    'type': 'string',
                }
            }
        }
    }
```
where there exists django model named ExampleModel.
```
class ExampleModel(models.Model):
    entity_field = models.CharField(max_length=32)
```

This feature might empower the functionalities of your cool library!

Thanks.

**Comment by bhch** [comment]
Hello, thank you for this suggestion. I like the idea. I will try to add something similar in the next version (but it will take some time).

I'll provide an autocomplete widget and when the user starts typing, it will send AJAX requests to the server.

Example:

```diff
 'model_id': {
     'title': 'entity',
     'type': 'number',
+    'widget': 'autocomplete',
+    'handler': '/url/of/ajax-view/'
 }
```

The requests will be made to your controlled view provided by the `handler` keyword. This puts you in complete control of what you want to return in the response. So this feature could be used for anything, not just foreign keys.

Let me know what you think.

**Comment by martincpt** [comment]
This sounds definitely interesting.

**Comment by zN3utr4l** [comment]
Take a look at this pkg: https://github.com/pyutil/django-admin-autocomplete-all

**Comment by bhch** [comment]
I've added an [Autocomplete widget](https://django-jsonform.readthedocs.io/en/latest/guide/autocomplete.html) in v2.12.0. It can be used for getting ForeignKey ids from the server. 

Please upgrade and test it out.
