### ISSUE TITLE
Issue with reactJsonForm.getFormInstance

### ISSUE THREAD

**Issue by jadwi2000** [bhch/django-jsonform#53]
Hi! I was trying to use function getFormInstance from reactJsonForm based on your [user's guide.](https://django-jsonform.readthedocs.io/en/latest/guide/javascript.html#reactjsonform-getforminstance-id) I did everything the exact same way as it was shown. It got inside this if  
```
window.addEventListener('load', function() {
    if (window.reactJsonForm) {
        var form = reactJsonForm.getFormInstance('id_my_field_jsonform');
        form.addEventListener('change', onJsonFormChange);
    }
});
```  
but then I got  "reactJsonForm.getFormInstance is not a function"  in console

**Comment by bhch** [comment]
It is working in the demo embedded on that page.

I'm guessing either you're using an older version or the browser is still loading stale static files from cache.

Please upgrade to the latest version. Also, make sure to "Disable Cache" in browser's network tab to get fresh static files.

If it still doesn't work, tell me which version you're using:

```shell
$ python -c "import django_jsonform; print(django_jsonform.__version__)"
```

**Comment by jadwi2000** [comment]
Thanks for help! As you suggested, I had an older django-jsonform version
