### ISSUE TITLE
multiselect not work

### ISSUE THREAD

**Issue by zN3utr4l** [bhch/django-jsonform#54]
The problem of selecting mentioned in issue #46 is still present in version 2.11.0

**Comment by bhch** [comment]
Make sure your browser is loading the latest JS files. Try and disable the cache in browser's *Dev tools*.

But that issue has been fixed. I've created some demos here: https://bhch.github.io/react-json-form/playground/. Take a look the at the **"Multi select choices"** tab. It uses a multiselect widget on the top level array.

If there' still problem after disabling cache, please provide a schema for me to reproduce this.

**Comment by zN3utr4l** [comment]
{
  "type": "array",
  "items": {
    "type": "integer",
    "choices": [
      {"label":"Test 1","value":1},
      {"label":"Test 2","value":2}
    ],
    "widget": "multiselect"
  }
}

**Comment by zN3utr4l** [comment]
this not work

**Comment by zN3utr4l** [comment]
![2022-08-30 10-17-45](https://user-images.githubusercontent.com/73225008/187387561-d2e2ce35-b0f4-4bae-a1d5-6b28ba800ee1.gif)

at first, when i was on the Array / List panel and not Multi Select choice, the behavior was this

**Comment by bhch** [comment]
Thank you for reporting this. It seems it only for string `value`. I'll fix it right away. Will release a minor version in a few hours.

**Comment by zN3utr4l** [comment]
Thanks

**Comment by bhch** [comment]
Fixed in [v2.11.1](https://github.com/bhch/django-jsonform/releases/tag/v2.11.1). Please upgrade.
