### ISSUE TITLE
Too space

### ISSUE THREAD

**Issue by zN3utr4l** [bhch/django-jsonform#55]
Is it possible to remove the excess space between the component and the help text?

![image](https://user-images.githubusercontent.com/73225008/188878072-d6cf3a13-cb67-42e0-b0cf-884fbe01323d.png)

**Comment by zN3utr4l** [comment]
django: 3.2.15
django-jsonform: 2.11.1

is the position of the help text correct?
![image](https://user-images.githubusercontent.com/73225008/189084060-771a4254-b301-4752-9645-21301e55e3cd.png)

otherwise, but not showing help text
![image](https://user-images.githubusercontent.com/73225008/189083984-c4d50915-83ab-40b9-9b15-0b40101c99b1.png)
![image](https://user-images.githubusercontent.com/73225008/189084084-7900933e-2ec9-4d34-b695-317401416544.png)


this is the html element, the help text div seams out, it's ok?
![image](https://user-images.githubusercontent.com/73225008/189085295-407ed046-afe2-4e6d-a2f1-42a13060aeaa.png)
![image](https://user-images.githubusercontent.com/73225008/189085583-ea722e59-8d97-4337-b66a-1343d54c3ead.png)

**Comment by zN3utr4l** [comment]
thanks, best support ever, it's my 3 issue solved :)

**Comment by bhch** [comment]
Fixed in [v2.12.0](https://github.com/bhch/django-jsonform/releases/tag/v2.12.0). Please upgrade.
