### ISSUE TITLE
Remove jQuery depency in widget template.

### ISSUE THREAD

**Issue by CearaWeir** [bhch/django-jsonform#59]
I modified the admin template and removed the jQuery. I prefer to use native js or react js.

This is a great project, and I would use it in other projects if it had to use jQuery.

Thank you.

**Comment by bhch** [comment]
Yes, it can be used without jQuery.

Currently, I'm using a bit of jQuery ([only one call](https://github.com/bhch/django-jsonform/blob/v2.11.1/django_jsonform/templates/django_jsonform/editor.html#L33)) to handle events related to inline models. Other than this one call, jQuery is not really a dependency.

Without jQuery, you'll just get a `ReferenceError` but the widget will still work. I'll switch to plain js for next version (which will be out in a few days).

**Comment by CearaWeir** [comment]
OK, Thank you.

**Comment by bhch** [comment]
Leave the issue open until I remove jquery calls.

**Comment by bhch** [comment]
Hello, I looked into this and it seems we'll have to keep the jQuery call in there.

When an inline admin form is added, Django emits a jQuery event called `"format:added"`. If the inline model has a `JSONField`, We listen to this event to render a new JSON widget.

It's not possible to listen for jQuery events from vanilla JS as jQuery implements its own event layer which can't be accessed from `document.addEventListener` or `window.addEventListener`.

If the page doesn't have jQuery, the widget will still work except when the widget is inside an inline model. In that case, browser will throw a `ReferenceError`.

If that ever becomes an issue for you, I suggest you [override the widget's template](https://docs.djangoproject.com/en/4.1/ref/forms/renderers/#overriding-built-in-widget-templates) and remove the jQuery call and implement your own way for handling inline forms.

Thank you for opening this issue.

**Comment by CearaWeir** [comment]
I will try, Thank you.

**Comment by bhch** [comment]
Update on this: The latest release [v2.13.0](https://github.com/bhch/django-jsonform/releases/tag/v2.13.0) no longer depends on jQuery for anything.
