### ISSUE TITLE
Additional keys can't contain dashes

### ISSUE THREAD

**Issue by pixerius** [bhch/django-jsonform#69]
Adding custom key with dash results in error on react-json-from library side: 
<img width="946" alt="Screenshot 2022-11-02 at 12 37 09" src="https://user-images.githubusercontent.com/6808568/199480311-91ef45b9-aba2-4fb2-96b6-381544feaba7.png">

For the above example the key was `test-test`.

**Comment by bhch** [comment]
Fixed in [v2.15.0](https://github.com/bhch/django-jsonform/releases/tag/v2.15.0). Please upgrade. Thank you for the bug report.
