### ISSUE TITLE
`DOMContentLoaded` Listener executes after DOM is already loaded, widget doesn't mount

### ISSUE THREAD

**Issue by martingouy** [bhch/django-jsonform#79]
Hello!

In our production environment, this listener executes after the DOM is already mounted, and thus, the widget doesn't mount:
https://github.com/bhch/django-jsonform/blob/bf968559d15e1e79e9be71fb121fec62dee8bdd1/django_jsonform/static/django_jsonform/index.js#LL2C35-L2C35

- We had to override it with `window.addEventListener('load'...` to get it working
- The problem didn't happen on local

Two questions:
- Are other people able to reproduce?
- `DOMContentLoaded` was added in this commit: https://github.com/bhch/django-jsonform/commit/eaf03c7e8c2fd039eb772b2a244b81d7bc142d91 . Any objection to changing it to `load` ? Happy to open a PR

**Comment by bhch** [comment]
- `DOMContentLoaded`: Fires after external scripts have been loaded and the DOM has been parsed. Doesn't wait for `async` scripts.
 - `load`: Fires after images, stylesheets, `async` scripts have been loaded.

Since we don't care about stylesheets and images, we want to render the widget as soon as the dependency scripts are available. So, we use the `DOMContentLoaded` event.

Only reason for it to not work is if the widget's script (index.js) is loaded as `async`.

**Comment by martingouy** [comment]
@bhch Thanks for your answer.
`index.js` is not loaded async in our case.

The weird thing is that listening to the `DOMContentLoaded` event on the `document` object vs `window` object does the trick. Not sure exactly why, but I'll keep digging

**Comment by bhch** [comment]
That's a great find! I just read some more about it and indeed, `document` is the primary target of `DOMContentLoaded` event. So, it initially fires on the `document` and then bubbles up to the `window` object.

It's hard to tell what's preventing it from bubbling in your case, but if it works on `document`, then that's what we'll use. You can open a PR if you wish.

**Comment by martingouy** [comment]
@bhch Sounds good. Just submitted a PR. Thank you for your work on this library.

**Comment by bhch** [comment]
Fixed in #80. I will release a new version in a couple of days.

**Comment by bhch** [comment]
Released the fix in [v2.15.0](https://github.com/bhch/django-jsonform/releases/tag/v2.15.0). Please upgrade. Thank you for the bug report.
