### ISSUE TITLE
Pass the model instance to schema callable

### ISSUE THREAD

**Issue by bhch** [bhch/django-jsonform#8]

**Comment by bhch** [comment]
This doesn't seem possible.

The form field and the widget is associated with a model field only once when the django process starts. Therefore, the widget has no way of accessing the model instance.

**Comment by martincpt** [comment]
Hi there,

I've just figured out how to implement this.

You are right, by default, it is really not possible to access model instance during the widget render process but it is possible to pass it if you have custom model admin form - which is highly likely - and if not, it's really not hard to create one.

```python
# admin.py
class FooAdminForm(forms.ModelForm):
    class Meta:
        model = Foo
        exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bar'].widget.instance = self.instance # passing instance to the field called bar

@admin.register(Foo)
class FooAdmin(admin.ModelAdmin):
    form = FooAdminForm
```

So how about giving the possibility for developers to access the instance if they really need it by just take look if there is an _instance_ attribute available in **widgets.JSONFormWidget** during the render method and pass it to shcema callable if there it is:

```python
# django_jsonform/widgets.py
class JSONFormWidget(forms.Widget):
    # from line 17
    def render(self, name, value, attrs=None, renderer=None):
        if callable(self.schema):
            instance = getattr(self, 'instance') if hasattr(self, 'instance') else None
            schema = self.schema() if instance is None else self.schema(instance)
        else:
            schema = self.schema
```

**Comment by bhch** [comment]
Okay, I'll add this. Seems like this is the best that can be done about this feature.

**Comment by bhch** [comment]
I've released this feature as per your suggestions in [version 2.8.0](https://github.com/bhch/django-jsonform/releases/tag/v2.8.0).

Thank you for this.

**Comment by martincpt** [comment]
Sounds promising! Thank you!
