### ISSUE TITLE
Admin form widget not appearing locally

### ISSUE THREAD

**Issue by lokeshwarobuli** [bhch/django-jsonform#90]
I am using the JSONField and ArrayField from the django-jsonform. Below are the screenshots from my local and staging environment. The arrayfields and jsonfields don't appear in the local admin console where they appear in the staging env. Am I missing some package or is there anything that you can help me with ?

Django-jsonform version : 2.15.0
Django version: 4.1

Local
<img width="1088" alt="Screenshot 2023-01-30 at 5 06 28 PM" src="https://user-images.githubusercontent.com/85650351/215466850-89eae1dc-67b5-44de-b051-d20223579937.png">

Staging
<img width="929" alt="Screenshot 2023-01-30 at 5 06 49 PM" src="https://user-images.githubusercontent.com/85650351/215466930-d9a3968f-470f-420c-b24f-b2975a1c63aa.png">

**Comment by bhch** [comment]
Are there any errors in your browser Console or Network log?

**Comment by lokeshwarobuli** [comment]
These were the console log errors when I load this page

<img width="1436" alt="Screenshot 2023-01-30 at 8 33 03 PM" src="https://user-images.githubusercontent.com/85650351/215513530-b36a3ccd-7463-4e61-ba5b-8fd3eaf99d5e.png">

**Comment by bhch** [comment]
It's hard to tell.

But you can try to check *"Disable Cache"* option in the Network tab and then reload the page.

 If that doesn't work, maybe try reinstalling with `pip insall -U django_jsonform`.

**Comment by lokeshwarobuli** [comment]
I tried, both of the ways you mentioned, but no luck. Thanks anyways also let me know if you come up with something

**Comment by lokeshwarobuli** [comment]
@bhch to add more context here, the console log errors appear only when I run things locally and when I run inside docker, things render perfectly fine

**Comment by bhch** [comment]
I'm unable to reproduce this error on my end. Maybe there are some directory permission issues?

**Comment by lokeshwarobuli** [comment]
@bhch, I found the issue that's causing this. I previously didn't have DEBUG env var set. So, I manually set DEBUG=TRUE for dev purposes. Then the form was working as expected
