### ISSUE TITLE
List of items not supported

### ISSUE THREAD

**Issue by shirecoding** [bhch/django-jsonform#97]
It seems that list of items is not supported?

```json
{
 "type": "array",
 "items" : [{
          "type": "string"
         },
         {
          "type": "integer"
         },
         {
          "type": "boolean"
         }
         ]
}
```

**Comment by bhch** [comment]
I don't think this is a valid Schema. The `items` keyword must be an object.

If you'd like to have multiple type of items in an array, I suggesting using `anyOf` keyword:

```json
{
 "type": "array",
 "items" : {
   "anyOf": [
     {"type": "string"},
     {"type": "integer"},
     {"type": "boolean"}
    ]
 }
}
```

**Comment by bhch** [comment]
I believe I've answered your question. I'm going to close this issue for now. If you, however, still think it's not resolved, feel free to reopen.
